version: "3.9"
services:
  mssqlserver:
      image: "mcr.microsoft.com/mssql/server:2022-latest"
      ports:
        - 1433:1433
      volumes:
        - ~/apps/mssql/data:/var/lib/mssql/data
      environment:
          MSSQL_SA_PASSWORD: "pass@word" ##pa$$w0rd
          ACCEPT_EULA: "Y"